[project]
name = "backend-training"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiomysql>=0.2.0",
    "aiosqlite>=0.22.1",
    "chromadb>=1.5.5",
    "fastapi>=0.135.2",
    "httpx>=0.27.0",
    "openai>=2.30.0",
    "pydantic>=2.0.0",
    "python-dotenv>=1.2.2",
    "redis>=5.0.0",
    "uvicorn>=0.42.0",
]
